jedzer/lab1.asm, jedzer/lab2.asm, jedzer/lab3.asm
Renamed files, added comments, optimized and redesigned output functions [LAB2-3], removed unused data in dataseg [LAB2-3] and renamed labels. Added NewLine procedure[LAB2-3].
=> [Malinouski Eugene] I'm sorry for making pull request with 3 lab works

annahdigital/lab1.asm
Вариант 1.  
```1) Если a ^ 3 > b ^ 2 то
Если c * d = a / b то
Результат = a AND b
Иначе
Результат = с
Иначе 
Результат = с * d + b.```
=> [Борисова Анна] Лабораторная работа 1.

KateChizhevskaya/lab1.ASM
В каждом из заданий переменные a, b, c, d определяются в сегменте данных и имеют размерность слово. Необходимо выполнить над ними заданные арифметические и логические операции, а результат поместить в регистр AX. При выполнении умножения считаем, что результат вмещается в слово. При выполнении деления считаем, что оно целочисленное.
Если a ^ 3 > b ^ 2 то
Если c * d = a / b то
Результат = a AND b
Иначе
Результат = с * d + b
Иначе
Результат = с
=> Чижевская Екатерина лабораторная 1

annahdigital/lab2.asm
Задание:
1) написать процедуру для вывода числа размерностью слово из регистра AX на экран
на входе число в регистре AX
на выходе это число на экране
все задействованные регистры должны быть сохранены в процедуре (т.е. все регистры,
значения которых каким-либо образом меняются внутри процедуры, должны быть
помещены в начале процедуры в стек и извлечены в конце процедуры в правильном порядке)
2) написать процедуру для ввода числа с клавиатуры в регистр AX
на входе пользовательский ввод
на выходе введенное число в регистре AX
все задействованные регистры должны быть сохранены в процедуре (кроме AX)
также должна быть проверка вводимого числа на правильность:
нельзя вводить не цифры, нельзя, например, ввести 70000
дополнительно можно реализовать обработку клавиши бэкспэйс (удалить один …
=> [Борисова Анна] Лабораторная работа 2.

annahdigital/lab4.asm
Лабораторная работа 4
Необходимо ввести строку с клавиатуры, сделать ее обработку согласно заданию и показать результат на экране. При выполнении работы необходимо использовать хотя бы одну из [команд для работы с цепочками] .
Вариант 1. 
Посчитать, сколько слов начинается с гласной буквы.
=> [Борисова Анна] Лабораторная работа 4.

cooseonfire/lab5.asm
=> LAb 5 without conflict

Sechko/lab1.asm
из 4 чисел найти наибольшее и записать в ax
=> [Сечко Антон] lab1(9)

Geniny/lab1.asm
5) Если a AND (a - 1) = b то
Если d > c + b то
Результат = c % d + c / d
Иначе
Результат = c XOR d
Иначе
Результат = b OR (b + 1)
=> Add first lab (Horbachev Dmitriy)

andrjak/LB1.asm
2) Если a AND b = c ^ 4 то
Результат = с / d / b + a
Иначе
Если c + b = a ^ 3 + b ^ 3 то
Результат = a XOR (b + c)
Иначе
Результат = b >> 3 (сдвинуть с три раза вправо)
=> [Валетко Андрей]Lab1

sechko/lab2.asm
Ввести с клавиатуры делимое и делитель, вывести их на экран, разделить, вывести результат.
=> [Сечко Антон]lab2

sechko2/lab4.asm
Найти и вывести самое длинное слово
=> [Сечко Антон]lab4

Geniny/lab3.asm
Задание:
1) написать процедуру для вывода знакового числа размерностью слово из регистра AX на экран
на входе число в регистре AX
на выходе это число на экране
все задействованные регистры должны быть сохранены в процедуре
2) написать процедуру для ввода знакового числа с клавиатуры в регистр AX
на входе пользовательский ввод, минус может быть только как первый символ
на выходе введенное число в регистре AX
все задействованные регистры должны быть сохранены в процедуре (кроме AX)
также должна быть проверка вводимого числа на правильность:
нельзя вводить не цифры, минус может быть только первым символом,
проверка на допустимые значения [-32768;32767]
дополнительно можно реализовать обработку клавиши бэкспэйс (удалить один
последний введенный символ) и клавиши ескэйп (удалить все число).
3) …
=> Lab3[Horbachev D.]

privetYaOmlet/lab1.asm
Вариант 2:
Если a AND b = c ^ 4 то
Результат = с / d / b + a
Иначе
Если c + b = a ^ 3 + b ^ 3 то
Результат = a XOR (b + c)
Иначе
Результат = b >> 3 (сдвинуть с три раза вправо)
=> Lab1[Матюшонак Александр]

annahdigital/lab5.asm
Вводятся размерности N и M и матрица размерности NxM. Необходимо найти сумму элементов, находящихся в четных столбах и показать эту сумму на экране.
=> lab 5 [Борисова Анна]

jedzer/lab7.cpp
Лабораторная работа 7
Создать оконное приложение, в котором на главном окне будет кнопка Clear. 
При щелчке мышью в любую точку нашего окна необходимо нарисовать небольшое изображение с центром в этой точке (например, елочку или домик).
Нажатие на кнопку Clear должно очищать наше окно. 
Работу надо выполнять без библиотек типа Windows Forms, а напрямую используя функции работы с окнами.
=> [Malinouski Eugene] lab7

annahdigital/lab6.asm, annahdigital/line.asm
Перекрыть девятую функцию прерывания 21h таким образом, чтобы в выводимой строке все гласные буквы были удалены.
=> Lab 6 (residental + test ). [Борисова Анна]

lab7.cpp
_Создать оконное приложение, в котором на главном окне будет кнопка Clear. При щелчке мышью в любую точку нашего окна необходимо нарисовать небольшое изображение с центром в этой точке (например, елочку или домик). Нажатие на кнопку Clear должно очищать наше окно. Работу надо выполнять без библиотек типа Windows Forms, а напрямую используя функции работы с окнами._
=> [Кузнечик Вероника] Lab7

surikatshka/6LR.asm, surikatshka/6lrTsr.asm, surikatshka/LAB7.cpp
=> [Gusakovskaya Arina] 7LAB

Geniny/lab4/lab4.asm
Необходимо ввести строку с клавиатуры, сделать ее обработку согласно заданию и показать результат на экране. При выполнении работы необходимо использовать хотя бы одну из [команд для работы с цепочками]. Считается, что строка состоит из слов, разделенных произвольным числом пробелов (за исключением вариантов 5, 6, 8, 9). Пробелы также могут располагаться перед первым словом и после последнего слова.
Удалить из строки все повторяющиеся символы (Оставить только первый символ из повторяющихся).
=> Lab4[Horbachev D.]

Geniny/lab5.asm
Лабораторная работа 5
Пятое задание посвящается двухмерным массивам. Каждый из них является прямоугольным, если не указано обратное (количество строк может быть отличным от количества столбцов).
Для задания массива необходимо ввести количество строк, затем количество столбцов и затем все элементы. 
Для ввода и вывода чисел использовать функции из 3 работы (работа со знаковыми числами), для простоты считать, что ввод всегда корректный (т.е. можно убрать все проверки на некорректность  из функций). 
При выводе на экран элементы одного столбца матрицы необходимо показывать друг под другом (разделять элементы символом табуляции).
Дополнительное задание на более высокую оценку: сделать ввод исходных матриц из файла, вывод результата в файл (название файлов можно задать в сегменте данных, …
=> Lab5[Horbachev D.]

andrjak/Lab5/LB5.asm
Лабораторная работа 5
Пятое задание посвящается двухмерным массивам. Каждый из них является прямоугольным, 
если не указано обратное (количество строк может быть отличным от количества столбцов). 
Для задания массива необходимо ввести количество строк, затем количество столбцов и затем все элементы. 
Для ввода и вывода чисел использовать функции из 3 работы (работа со знаковыми числами), для простоты считать, 
что ввод всегда корректный (т.е. можно убрать все проверки на некорректность  из функций). 
При выводе на экран элементы одного столбца матрицы необходимо показывать друг под другом (разделять элементы символом табуляции).
Дополнительное задание на более высокую оценку: сделать ввод исходных матриц из файла, вывод результата в файл (название файлов можно задать в сегменте данных, …
=> Lab5[Валетко Андрей]

andrjak/Lab6/Lab6.asm
Лабораторная работа 6
Необходимо перекрыть указанный в задании обработчик прерывания и заставить его выполнять нужные действия. В большинстве случаев необходим вызов предыдущего обработчика. Также должна быть отдельная небольшая программа, демонстрирующая работу перекрытого обработчика. 
Программа должна состоять из резидентной части и инсталяционной части. Первая из них отвечает за работу с перекрываемым прерыванием. А инсталяционная часть должна вызываться при старте программы и отвечать за установку обработчиков.
Инсталяционная часть должна уметь прочитать командную строку:
а) если нам не передается параметров:
- если обработчик уже установлен: выдать сообщение об этом и выйти из программы
- если обработчик еще не установлен: сохранить адрес старого обработчика, установить наш …
=> Lab6[Валетко Андрей]

privetYaOmlet/Lab2/L2.asm
1) написать процедуру для вывода числа размерностью слово из регистра AX на экран
на входе число в регистре AX
на выходе это число на экране
все задействованные регистры должны быть сохранены в процедуре (т.е. все регистры,
значения которых каким-либо образом меняются внутри процедуры, должны быть
помещены в начале процедуры в стек и извлечены в конце процедуры в правильном порядке)
2) написать процедуру для ввода числа с клавиатуры в регистр AX
на входе пользовательский ввод
на выходе введенное число в регистре AX
все задействованные регистры должны быть сохранены в процедуре (кроме AX)
также должна быть проверка вводимого числа на правильность:
нельзя вводить не цифры, нельзя, например, ввести 70000
дополнительно можно реализовать обработку клавиши бэкспэйс (удалить один
последний …
=> lab2[Matyushonak A.D.]

privetYaOmlet/Lab3/L3.asm
1) написать процедуру для вывода знакового числа размерностью слово из регистра AX на экран
на входе число в регистре AX
на выходе это число на экране
все задействованные регистры должны быть сохранены в процедуре
2) написать процедуру для ввода знакового числа с клавиатуры в регистр AX
на входе пользовательский ввод, минус может быть только как первый символ
на выходе введенное число в регистре AX
все задействованные регистры должны быть сохранены в процедуре (кроме AX)
также должна быть проверка вводимого числа на правильность:
нельзя вводить не цифры, минус может быть только первым символом,
проверка на допустимые значения [-32768;32767]
дополнительно можно реализовать обработку клавиши бэкспэйс (удалить один
последний введенный символ) и клавиши ескэйп (удалить все число).
3) в …
=> lab3[Matyushonak A.D.]

Geniny/lab7/lab7.txt
Лабораторная работа 7
Разработка оконного приложения под платформу Win32
Создать оконное приложение, в котором на главном окне будет кнопка Clear. При щелчке мышью в любую точку нашего окна необходимо нарисовать небольшое изображение с центром в этой точке (например, елочку или домик). Нажатие на кнопку Clear должно очищать наше окно. Работу надо выполнять без библиотек типа Windows Forms, а напрямую используя функции работы с окнами.
=> Lab7[Horbachev D.]

sechko/lab6.asm
Вместо гласных букв показать следующие за ними по алфавиту
=> lab6[Сечко Антон]

KlishevichIlya/р.txt
New branch because  I crashed  my first branch.
=> Lab7(Klishevich)

privetYaOmlet/Lab4/L4.asm
Удалить из строки все повторяющиеся символы (Оставить только первый символ из повторяющихся).
=> Lab4[Matyushonak A.]

AntonSilebin/lab1.asm, AntonSilebin/lab2.asm
=> Lab2(updated)
